version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    groups:
      gha:
        patterns:
          - "*"
- package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
- package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      pip:
        patterns:
          - "*"
